# Generated by Django 5.2.3 on 2025-08-29 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sertifika Adı')),
                ('organization', models.CharField(max_length=200, verbose_name='Veren Kurum')),
                ('date_received', models.DateField(verbose_name='Alınma Tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='Sertifika ID')),
                ('credential_url', models.URLField(blank=True, verbose_name='Sertifika URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifika Görseli')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
                'ordering': ['-date_received', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('lisans', 'Lisans'), ('yuksek_lisans', 'Yüksek Lisans'), ('doktora', 'Doktora'), ('sertifika', 'Sertifika')], max_length=20, verbose_name='Derece')),
                ('school', models.CharField(max_length=200, verbose_name='Okul/Kurum')),
                ('department', models.CharField(max_length=200, verbose_name='Bölüm')),
                ('start_year', models.IntegerField(verbose_name='Başlangıç Yılı')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='Bitiş Yılı')),
                ('location', models.CharField(max_length=100, verbose_name='Şehir')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_current', models.BooleanField(default=False, verbose_name='Devam Ediyor')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitimler',
                'ordering': ['-start_year', '-order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Pozisyon')),
                ('company', models.CharField(max_length=200, verbose_name='Şirket')),
                ('location', models.CharField(max_length=100, verbose_name='Şehir')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_current', models.BooleanField(default=False, verbose_name='Mevcut Pozisyon')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deneyim',
                'verbose_name_plural': 'Deneyimler',
                'ordering': ['-start_date', '-order'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Okan Kantar', max_length=100, verbose_name='Ad Soyad')),
                ('title', models.CharField(default='Full Stack Developer', max_length=200, verbose_name='Ünvan')),
                ('bio', models.TextField(help_text='Ana sayfada görünecek kısa tanıtım', verbose_name='Kısa Tanıtım')),
                ('about_text', models.TextField(help_text='Hakkımda sayfasında görünecek detaylı metin', verbose_name='Hakkımda Metni')),
                ('birth_year', models.IntegerField(default=1989, verbose_name='Doğum Yılı')),
                ('location', models.CharField(default='Ankara, Türkiye', max_length=100, verbose_name='Lokasyon')),
                ('email', models.EmailField(default='okkant@gmail.com', max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(default='0539 315 6407', max_length=20, verbose_name='Telefon')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profil Fotoğrafı')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='CV Dosyası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kişisel Bilgi',
                'verbose_name_plural': 'Kişisel Bilgiler',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('category', models.CharField(choices=[('web', 'Web Uygulaması'), ('desktop', 'Masaüstü Uygulaması'), ('mobile', 'Mobil Uygulama'), ('api', 'API Projesi'), ('website', 'Web Sitesi'), ('other', 'Diğer')], max_length=20, verbose_name='Kategori')),
                ('status', models.CharField(choices=[('completed', 'Tamamlandı'), ('in_progress', 'Devam Ediyor'), ('planned', 'Planlandı')], default='completed', max_length=20, verbose_name='Durum')),
                ('short_description', models.TextField(max_length=300, verbose_name='Kısa Açıklama')),
                ('description', models.TextField(verbose_name='Detaylı Açıklama')),
                ('technologies', models.CharField(help_text='Virgülle ayırın', max_length=500, verbose_name='Kullanılan Teknolojiler')),
                ('features', models.TextField(help_text='Her satıra bir özellik', verbose_name='Özellikler')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Proje Görseli')),
                ('demo_url', models.URLField(blank=True, verbose_name='Demo URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-created_date', '-order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Okan Kantar', max_length=100, verbose_name='Site Başlığı')),
                ('site_description', models.TextField(verbose_name='Site Açıklaması')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta Anahtar Kelimeler')),
                ('footer_text', models.CharField(default='© 2024 Okan Kantar. Tüm hakları saklıdır.', max_length=200, verbose_name='Footer Metni')),
                ('google_analytics_id', models.CharField(blank=True, max_length=20, verbose_name='Google Analytics ID')),
                ('hero_title', models.CharField(default='Merhaba, Ben Okan Kantar', max_length=200, verbose_name='Hero Başlık')),
                ('hero_subtitle', models.CharField(default='Full Stack Developer', max_length=200, verbose_name='Hero Alt Başlık')),
                ('hero_description', models.TextField(verbose_name='Hero Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yetenek Adı')),
                ('category', models.CharField(choices=[('programming', 'Programlama Dilleri'), ('framework', 'Framework ve Kütüphaneler'), ('database', 'Veritabanları'), ('tool', 'Araçlar ve Teknolojiler'), ('soft', 'Kişisel Beceriler')], max_length=20, verbose_name='Kategori')),
                ('level', models.IntegerField(help_text='0-100 arası değer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seviye (%)')),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome sınıfı (örn: fab fa-python)', max_length=100, verbose_name='İkon Sınıfı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
                'ordering': ['category', '-level', 'order'],
            },
        ),
    ]
